services:
  frontend:
    build: ./frontend
    ports:  
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "5001:8080"
    depends_on:
      - flask
      - db
  flask:
    build: ./flask-server
    ports:
      - "5001:5000"
  db:
    build: ./db
    ports:
      - "3306:3306"