services:
  frontend:
    build: ./frontend
    ports:  
      - "3000:80"
    networks:
      - scrapsat
  backend:
    build: ./backend
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DataBaseConnection=server=db;port=3306;database=dbfmicodes;user=root;password=Walhalen_3pich;
      - ConnectionStrings__flaskApiUrl=http://flask:5000/possibility_of_collision
    depends_on:
      - flask
      - db
    networks:
      - scrapsat
  flask:
    build: ./flask-server
    ports:
      - "5000:5000"
    networks:
      - scrapsat
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Walhalen_3pich
      MYSQL_DATABASE: dbfmicodes
    ports:
        - '33306:3306'
    volumes:
      - ./DB/dbInit.sql:/docker-entrypoint-initdb.d/dbInit.sql
    networks:
      - scrapsat
networks:
  scrapsat:
    driver: bridge
