/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 debris.gltf 
Author: Rurre (https://sketchfab.com/rurre)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scrap-metal-1e57de80d46442a38c8c5b2fb06888f4
Title: Scrap Metal
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/debris.gltf')
  return (
    <group {...props} dispose={null}>
        <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.scrap}
            position={[-2, 0, 1]}
            scale={0.1}
        />
    </group>
  )
}

useGLTF.preload('/debris.gltf')
