/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 satellite.gltf 
Author: arttuGlz (https://sketchfab.com/arttuGlz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/satelite-bb4f51e762a94dd9b9bdb348165f2bcd
Title: Satelite
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/satellite.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/satellite.gltf')
